/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

/**
 *
 * @author asus_
 */
public class ListMember extends javax.swing.JPanel {

    /**
     * Creates new form ListMember
     */
    public ListMember() {
        initComponents();
    }
    
    public void setData(String nama, String no_hp, int kunjungan, int poin, String tier) {
        lblNamaMember.setText(nama);
        lblTelepon.setText(no_hp);
        lblJmlKunjungan.setText(kunjungan + " kunjungan");
        lblPoin.setText(poin + " poin");
        lblTier.setText(tier);

        if (tier.equalsIgnoreCase("Bronze")) {
            badgeTier.setBackground(new java.awt.Color(205, 127, 50));
            lblTier.setForeground(new java.awt.Color(255, 255, 255));
        } else if (tier.equalsIgnoreCase("Silver")) {
            badgeTier.setBackground(new java.awt.Color(192, 192, 192));
            lblTier.setForeground(new java.awt.Color(0, 0, 0));
        } else { // Gold
            badgeTier.setBackground(new java.awt.Color(255, 215, 0));
            lblTier.setForeground(new java.awt.Color(0, 0, 0));
        }
        this.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(50, 50, 50)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamaMember = new javax.swing.JLabel();
        lblTelepon = new javax.swing.JLabel();
        lblJmlKunjungan = new javax.swing.JLabel();
        lblJmlKunjungan1 = new javax.swing.JLabel();
        badgeTier = new javax.swing.JPanel();
        lblTier = new javax.swing.JLabel();
        lblPoin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(22, 22, 26));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(400, 60));

        lblNamaMember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamaMember.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaMember.setText("Nama Member");

        lblTelepon.setForeground(new java.awt.Color(255, 255, 255));
        lblTelepon.setText("0892424343");

        lblJmlKunjungan.setForeground(new java.awt.Color(255, 255, 255));
        lblJmlKunjungan.setText("5 kunjungan");

        lblJmlKunjungan1.setForeground(new java.awt.Color(255, 255, 255));
        lblJmlKunjungan1.setText("|");

        badgeTier.setBackground(new java.awt.Color(204, 153, 0));

        lblTier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTier.setText("Gold");

        javax.swing.GroupLayout badgeTierLayout = new javax.swing.GroupLayout(badgeTier);
        badgeTier.setLayout(badgeTierLayout);
        badgeTierLayout.setHorizontalGroup(
            badgeTierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(badgeTierLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        badgeTierLayout.setVerticalGroup(
            badgeTierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        lblPoin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPoin.setForeground(new java.awt.Color(201, 168, 76));
        lblPoin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPoin.setText("300 poin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelepon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJmlKunjungan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJmlKunjungan))
                    .addComponent(lblNamaMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(badgeTier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPoin)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNamaMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelepon)
                            .addComponent(lblJmlKunjungan)
                            .addComponent(lblJmlKunjungan1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPoin)
                            .addComponent(badgeTier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel badgeTier;
    private javax.swing.JLabel lblJmlKunjungan;
    private javax.swing.JLabel lblJmlKunjungan1;
    private javax.swing.JLabel lblNamaMember;
    private javax.swing.JLabel lblPoin;
    private javax.swing.JLabel lblTelepon;
    private javax.swing.JLabel lblTier;
    // End of variables declaration//GEN-END:variables
}
